// js/artifacts.js
const artifacts = [
    {
        id: 'bronze-flower-bird-basin',
        zh_name: '青铜花鸟树盆',
        en_name: 'Bronze Flower and Bird Tree Basin',
        image: 'images/bronze_basin_thumb.png',
        model: 'models/fishpond.glb',
        zh_desc: '战国时期（公元前475-221年）青铜器，器身以浮雕工艺饰有花鸟树木图案。战国时期是中国历史上思想文化极为活跃的时代，诸子百家争鸣，艺术创作也呈现出多样化的特点。青铜器在这一时期逐渐从礼器向实用器转变，装饰风格更加写实自然。花鸟树盆的出现反映了当时人们对自然美的追求和对生活品质的提升，体现了战国时期"天人合一"的哲学思想。此盆采用失蜡法铸造工艺，先制作蜡模，再在外包裹泥范，加热后蜡液流出形成空腔，最后浇注青铜溶液。器身浮雕采用分层雕刻技法，花鸟树木图案层次分明，线条流畅。表面经过抛光处理，部分区域可能还使用了镶嵌工艺，以突出纹饰的立体效果。整个制作过程需要高超的金属加工技术和艺术表现力。',
        en_desc: 'A bronze vessel from the Warring States period (475-221 BCE), the body is decorated with flower, bird, and tree patterns using relief carving. The Warring States period was an era of extremely active ideological and cultural development in Chinese history, with the contention of various schools of thought and diverse artistic creations. Bronze vessels gradually transitioned from ritual objects to practical utensils during this period, with decorative styles becoming more realistic and natural. The emergence of flower and bird tree basins reflected the contemporary pursuit of natural beauty and improvement of life quality, embodying the philosophical concept of "harmony between heaven and humanity" from that era. This basin was created using the lost-wax casting process, where a wax model is first made, then covered with clay molds. After heating, the wax flows out to form a cavity, and finally bronze solution is poured in. The body relief uses layered carving techniques, with distinct layers of flower, bird, and tree patterns and smooth lines. The surface is polished, and some areas may have used inlay techniques to enhance the three-dimensional effect of the decorations. The entire production process requires superb metalworking technology and artistic expression.'
    },
    {
        id: 'sancai-horse',
        zh_name: '唐三彩马',
        en_name: 'Tang Sancai Horse',
        image: 'images/terracotta_warrior_thumb.png',
        model: 'models/cheval.glb',
        zh_desc: '唐代（618-907年）低温铅釉陶器，以黄、绿、白三色釉为主。唐三彩盛行于唐代，特别是唐高宗至唐玄宗时期，是唐代陶瓷工艺的杰出代表。这一时期唐朝国力强盛，对外交流频繁，丝绸之路贸易繁荣，贵族阶层崇尚奢华生活。三彩器主要作为随葬品，反映了唐代"事死如事生"的丧葬观念，以及当时社会对马匹的重视——马不仅是交通和战争工具，更是身份和财富的象征。马匹造型健硕，形态生动，是唐代墓葬中常见的随葬品，用于表现墓主人的身份与财富。采用两次烧成工艺：先素烧胎体至800-900°C，然后施釉再进行低温（800°C左右）铅釉烧制。釉料以铜、铁、锰等金属氧化物为着色剂，在烧制过程中自然流淌形成独特的斑驳效果。马匹造型采用模制与手工结合，先分段制作再拼接成型。工匠们精准控制釉料配比和烧制温度，使不同颜色的釉在烧制过程中相互浸润，形成绚丽多彩的艺术效果。',
        en_desc: 'A low-temperature lead-glazed pottery from the Tang Dynasty (618-907 CE), primarily featuring yellow, green, and white glazes. Tang Sancai prevailed during the Tang Dynasty, especially from the reign of Emperor Gaozong to Emperor Xuanzong, representing the excellence of Tang Dynasty ceramic craftsmanship. During this period, the Tang Dynasty was powerful, with frequent foreign exchanges and prosperous Silk Road trade. The aristocracy pursued luxurious lifestyles. Sancai wares were mainly used as burial objects, reflecting the Tang concept of "treating the dead as if they were alive" and the contemporary social importance of horses—horses were not only means of transportation and tools of war but also symbols of status and wealth. The horse is robustly shaped and vividly formed, a common burial item in Tang tombs used to represent the status and wealth of the deceased. Uses a two-firing process: first bisque-firing the body at 800-900°C, then applying glaze and firing again at low temperature (around 800°C) with lead glaze. The glaze uses metal oxides such as copper, iron, and manganese as colorants, which naturally flow during firing to create unique mottled effects. The horse shape is created using a combination of mold-making and handcrafting, with segments made separately and then assembled. Artisans precisely control glaze ratios and firing temperatures, allowing different colored glazes to interpenetrate during firing, creating splendid and colorful artistic effects.'
    },
    {
        id: 'tang-official',
        zh_name: '唐代文官俑',
        en_name: 'Tang Dynasty Official Figurine',
        image: 'images/tang-official.png',
        model: 'models/tang_official.glb',
        zh_desc: '唐代墓葬出土的陶质文官俑。唐代文官俑通常出土于中高级官员墓葬中，反映了唐代完善的官僚制度和严格的等级制度。唐代实行三省六部制，官员分为九品三十阶，服饰和仪态都有严格规定。文官俑作为随葬品，体现了"事死如事生"的观念，希望墓主人在来世继续享受生前的地位和荣耀。这些陶俑也是研究唐代服饰文化、官制礼仪的重要实物资料。其服饰与姿态遵循当时的礼制，采用模制与手工结合的工艺制作。先制作主体模具，然后分别制作头部、手臂等部件，最后组装成型。表面施以白釉或黄釉作为底色，再使用彩绘工艺绘制服饰纹样和面部表情。彩绘颜料多采用矿物颜料，色彩鲜艳持久。文官俑的服饰细节如袍服褶皱、腰带装饰等都经过精细处理，展现了唐代陶工高超的造型能力和对细节的把握。',
        en_desc: 'A pottery official figurine unearthed from a Tang Dynasty tomb. Tang Dynasty official figurines are usually unearthed from middle and high-ranking official tombs, reflecting the perfect bureaucratic system and strict hierarchy of the Tang Dynasty. The Tang implemented the Three Provinces and Six Ministries system, with officials divided into nine ranks and thirty grades, with strict regulations on clothing and demeanor. As burial objects, official figurines embodied the concept of "treating the dead as if they were alive," hoping the tomb owner would continue to enjoy their status and glory in the afterlife. These pottery figurines are also important physical materials for studying Tang Dynasty dress culture and official ritual systems. Its attire and posture follow the ritual system of the time, created using a combination of mold-making and handcrafting. First, the main mold is made, then components like the head and arms are created separately, and finally assembled. The surface is applied with white or yellow glaze as a base color, then colorful painting techniques are used to draw costume patterns and facial expressions. The pigments mostly use mineral colors, which are bright and long-lasting. Details of the official\'s clothing, such as robe folds and belt decorations, are finely processed, demonstrating the high modeling ability and attention to detail of Tang Dynasty potters.'
    },
    {
        id: 'western-zhou-zhe-gong',
        zh_name: '西周折觥',
        en_name: 'Western Zhou Zhe Gong',
        image: 'images/western_zhou_gong_thumb.png',
        model: 'models/lidded.glb',
        zh_desc: '西周时期（公元前1046-771年）青铜酒器，有盖，盖前端为兽首，后端作鸟形。西周时期是中国青铜礼器发展的鼎盛时期，青铜器不仅是实用器具，更是权力和地位的象征。觥是古代盛酒或饮酒的器具，多用于重要祭祀和宴飨场合。折觥的精美装饰反映了西周"礼乐文化"的特点，以及当时人们对神灵和祖先的敬畏。器物上的夔龙纹和鸟纹都具有特定的象征意义，体现了西周时期的宗教信仰和宇宙观念。器身饰有夔龙纹、鸟纹等，是西周青铜礼器的典型器物。采用块范法铸造工艺，需要制作外范、内范和泥芯等多个部件。器身纹饰采用范铸法，在泥范上雕刻纹饰，浇注时纹饰自然形成。盖部的兽首和鸟形装饰采用分铸法，先单独铸造再与器身连接。整个器物制作需要精确计算合金比例（铜、锡、铅），控制浇注温度和冷却速度。表面可能还经过打磨和抛光处理，使纹饰更加清晰立体。',
        en_desc: 'A bronze wine vessel from the Western Zhou Dynasty (1046-771 BCE), with a lid. The front of the lid is shaped like an animal head, and the back is shaped like a bird. The Western Zhou period was the golden age of Chinese bronze ritual vessel development, when bronze objects were not only practical utensils but also symbols of power and status. The gong was an ancient vessel for holding or drinking wine, mostly used in important sacrificial and banquet occasions. The exquisite decoration of the Zhe Gong reflects the characteristics of Western Zhou "ritual and music culture" and the contemporary reverence for gods and ancestors. The kui dragon and bird patterns on the vessel have specific symbolic meanings, reflecting the religious beliefs and cosmological concepts of the Western Zhou period. The body is decorated with patterns like kui dragons and birds, a typical artifact of Western Zhou bronze ritual vessels. Uses the piece-mold casting process, requiring multiple components including outer molds, inner molds, and clay cores. The body decoration is created using mold casting, with patterns carved into the clay molds that naturally form during pouring. The animal head and bird-shaped decorations on the lid are made using separate casting, first cast individually then connected to the vessel body. The entire vessel production requires precise calculation of alloy ratios (copper, tin, lead) and control of pouring temperature and cooling speed. The surface may also be polished and buffed to make the patterns clearer and more three-dimensional.'
    },
    {
        id: 'headless-buddha-statue',
        zh_name: '无头佛造像',
        en_name: 'Headless Buddha Statue',
        image: 'images/headless_buddha_thumb.png',
        model: 'models/fo.glb',
        zh_desc: '石质佛教造像，头部已缺失。唐代（618-907年）是中国佛教艺术发展的黄金时期，佛像造像风格从早期的清瘦转变为丰腴饱满，体现了盛唐时期繁荣昌盛的社会风貌和审美取向。无头佛像多因历史上的灭佛运动或自然损坏而致，如唐武宗会昌灭佛（845年）期间大量佛像被毁。这些残存的造像仍然具有重要的艺术和历史价值，是研究唐代佛教雕塑艺术的重要实物资料。从残存的躯干部分可见其衣纹流畅，体态丰腴，具有唐代佛像的典型风格特征。选用优质石材，如石灰石或砂岩，采用整块石料雕刻而成。雕刻工艺采用减地法，先大致勾勒轮廓，再逐步细化。衣纹处理采用流畅的阴刻线条，表现出衣物的轻薄质感。佛像身体比例遵循"相好"标准，体现了佛教造像仪轨的要求。表面可能还经过彩绘和贴金装饰，虽然现在多已剥落，但从残留痕迹仍可想象当年的辉煌。',
        en_desc: 'A stone Buddhist statue, the head is missing. The Tang Dynasty (618-907 CE) was the golden age of Chinese Buddhist art development, when Buddha statue styles transformed from early slender forms to plump and full ones, reflecting the prosperous social conditions and aesthetic orientation of the high Tang period. Headless Buddha statues were mostly caused by historical anti-Buddhist movements or natural damage, such as the large-scale destruction of Buddha statues during Emperor Wuzong\'s Huichang anti-Buddhist campaign (845 CE). These remaining statues still have important artistic and historical value, serving as important physical materials for studying Tang Dynasty Buddhist sculpture art. The remaining torso shows smooth drapery lines and a plump body, which are typical stylistic features of Tang Dynasty Buddha statues. Made from high-quality stone such as limestone or sandstone, carved from a single block. The carving process uses the reduction method, first roughly outlining the shape, then gradually refining details. The drapery treatment uses smooth incised lines to express the light texture of the clothing. The Buddha\'s body proportions follow the "lakshana" standards, reflecting the requirements of Buddhist iconography. The surface may have been decorated with painting and gold leaf, although most has now peeled off, but remaining traces still allow us to imagine its original splendor.'
    },
    {
        id: 'buddha-statue',
        zh_name: '佛造像',
        en_name: 'Buddha Statue',
        image: 'assets/images/buddha_statue_thumb.jpg',
        model: 'models/cosmic.glb',
        zh_desc: '石质佛教造像。佛教自汉代传入中国后，经过魏晋南北朝的发展，到唐代达到鼎盛。佛像造像艺术也经历了从外来风格到中国化的过程。这尊佛像体现了中国佛教艺术的成熟风格，融合了印度造像仪轨与中国传统审美。佛像的手印、坐姿都有特定的宗教含义，反映了佛教教义和修行方式。这类造像多安置于寺庙或石窟中，供信徒礼拜瞻仰。佛像结跏趺坐，手结印相，面相庄严。采用圆雕技法，选用质地细腻的石料，如汉白玉或青石。雕刻过程遵循严格的造像仪轨，从头部的发髻、面相到身体的比例、衣纹都有规范。佛像面部表情庄严肃穆，双眼微闭，表现出禅定状态。衣纹处理采用层次分明的雕刻技法，既表现出衣物的褶皱，又不失整体的和谐统一。表面可能还施有彩绘，虽然历经岁月多已褪色，但雕刻本身的精湛技艺依然清晰可见。整体雕刻技法娴熟，是古代佛教雕塑艺术的实物例证。',
        en_desc: 'A stone Buddhist statue. After Buddhism was introduced to China during the Han Dynasty, it developed through the Wei, Jin, and Southern and Northern Dynasties, reaching its peak in the Tang Dynasty. Buddhist statue art also experienced a process from foreign styles to Sinicization. This Buddha statue embodies the mature style of Chinese Buddhist art, integrating Indian iconographic standards with traditional Chinese aesthetics. The Buddha\'s hand gestures and sitting posture have specific religious meanings, reflecting Buddhist doctrines and practices. Such statues were mostly placed in temples or grottoes for believers to worship and admire. The Buddha is seated in a lotus position with hands in a mudra, featuring a solemn facial expression. Created using round carving techniques, selecting fine-grained stone such as white marble or bluestone. The carving process follows strict iconographic rules, with regulations for everything from the hair topknot and facial features to body proportions and drapery. The Buddha\'s facial expression is solemn and dignified, with eyes slightly closed, showing a meditative state. The drapery treatment uses distinct layered carving techniques that both express the folds of the clothing while maintaining overall harmony and unity. The surface may have been painted, although most has faded over time, but the exquisite skill of the carving itself remains clearly visible. The overall carving technique is skillful, serving as a physical example of ancient Buddhist sculptural art.'
    },
    {
        id: 'tiger-bird-gong',
        zh_name: '虎鸟兽纹觥',
        en_name: 'Tiger and Bird Pattern Gong',
        image: 'images/tiger_bird_gong_thumb.png',
        model: 'models/gong.glb',
        zh_desc: '商代晚期（公元前1300-1046年）青铜酒器。商代晚期是中国青铜器发展的巅峰时期，青铜器制作技术达到空前高度。觥作为重要的礼器，主要用于祭祀和宴飨场合，是商代贵族身份和权力的象征。虎、鸟等动物纹饰在商代青铜器中常见，反映了商代人的图腾崇拜和宗教信仰。这些纹饰不仅具有装饰功能，更承载着沟通天地、驱邪避凶的宗教意义。器身饰有虎、鸟等兽面纹，造型厚重，纹饰繁缛，是商代青铜礼器的重要组成部分。采用复合范铸造工艺，需要制作复杂的外范和内范。器身的兽面纹采用三层叠铸技术，使纹饰具有强烈的立体感。虎、鸟等动物形象造型夸张生动，展现了商代工匠丰富的想象力和高超的雕刻技巧。器物整体厚重稳固，体现了商代青铜器"以重为贵"的审美特点。铸造完成后，表面还可能经过精细打磨和抛光，使纹饰更加清晰。',
        en_desc: 'A bronze wine vessel from the late Shang Dynasty (1300-1046 BCE). The late Shang Dynasty was the peak period of Chinese bronze development, when bronze production technology reached unprecedented heights. As an important ritual vessel, the gong was mainly used for sacrificial and banquet occasions, symbolizing the status and power of Shang nobility. Animal patterns like tigers and birds were common on Shang Dynasty bronzes, reflecting the totem worship and religious beliefs of the Shang people. These decorations not only had decorative functions but also carried religious meanings of communicating between heaven and earth and warding off evil spirits. The body is decorated with animal mask patterns including tigers and birds. It has a heavy form and intricate decorations, an important component of Shang Dynasty bronze ritual vessels. Uses composite mold casting technology, requiring complex outer and inner molds. The animal mask patterns on the vessel body employ three-layer overlay casting technology, giving the decorations a strong three-dimensional effect. The animal images like tigers and birds are exaggerated and vivid, showcasing the rich imagination and superb carving skills of Shang artisans. The overall vessel is heavy and stable, reflecting the Shang Dynasty bronze aesthetic of "valuing weight." After casting completion, the surface may also be finely polished and buffed to make the patterns clearer.'
    },
    {
        id: 'tang-palace-lady-figurine',
        zh_name: '唐代宫女造像',
        en_name: 'Tang Dynasty Palace Lady Figurine',
        image: 'images/tang_palace_lady_thumb.png',
        model: 'models/nv.glb',
        zh_desc: '唐代墓葬出土的陶质宫女俑。唐代宫廷女性造像反映了盛唐时期开放包容的社会风貌和独特的审美观念。唐代女性地位相对较高，宫女在宫廷生活中扮演重要角色。这些陶俑多出土于贵族墓葬，体现了"事死如事生"的丧葬观念，希望墓主人在来世继续有侍女服侍。丰腴的体态是唐代审美的典型特征，与当时社会繁荣、物质丰富的背景密切相关。其体态丰腴，身着宫装，造型反映了唐代宫廷女性的形象与服饰特点。采用模制与手工结合的工艺。先制作主体模具，然后手工修饰面部表情和服饰细节。宫女俑的服饰层次丰富，包括内衫、外袍、披帛等，都需要精细处理。彩绘工艺是关键，使用矿物颜料绘制服饰图案和面部妆容。唐代彩绘技术高超，能够表现出丝绸的质感和服饰的华丽。发髻造型复杂多变，展现了唐代女性的发式美学。',
        en_desc: 'A pottery palace lady figurine unearthed from a Tang Dynasty tomb. Tang Dynasty palace lady figurines reflect the open and inclusive social atmosphere and unique aesthetic concepts of the high Tang period. Women had relatively high status in the Tang Dynasty, and palace maids played important roles in court life. These pottery figurines are mostly unearthed from noble tombs, embodying the concept of "treating the dead as if they were alive," hoping the tomb owner would continue to have maids serving in the afterlife. The plump figure is a typical feature of Tang aesthetics, closely related to the prosperous and materially rich background of that society. It has a plump figure and wears palace attire, its form reflecting the image and clothing characteristics of court women in the Tang Dynasty. Created using a combination of mold-making and handcrafting. First, the main mold is made, then facial expressions and clothing details are manually refined. The palace lady figurine\'s clothing has rich layers, including inner shirts, outer robes, and silk sashes, all requiring fine treatment. The painting process is key, using mineral pigments to draw costume patterns and facial makeup. Tang Dynasty painting techniques were superb, capable of expressing the texture of silk and the gorgeousness of clothing. The hairstyle is complex and varied, showcasing the hair aesthetics of Tang women.'
    },
    {
        id: 'bronze-jue',
        zh_name: '青铜酒爵',
        en_name: 'Bronze Jue',
        image: 'images/bronze_jue_thumb.png',
        model: 'models/jue.glb',
        zh_desc: '商代早期（公元前1600-1046年）青铜酒器。青铜爵是商代最早出现的青铜酒器之一，是商代礼器制度的重要组成部分。商代社会高度重视祭祀活动，酒器在祭祀中具有关键作用。爵的形制设计科学合理，流便于倾倒，尾防止酒液溢出，柱可用于悬挂装饰或固定。三足设计不仅稳固，还便于在火上加热温酒。青铜爵的出现标志着中国青铜时代的开始，是中华文明进入高级阶段的重要标志。器型前有流，后有尾，中有柱，下有三足。是商代青铜礼器中基本的温酒或饮酒器具。采用早期青铜铸造技术，使用简单的双合范或复合范。器壁较薄，反映了早期青铜铸造技术的特点。流、尾、足等部件可能采用分铸法制作，然后与器身连接。器表纹饰简单，多为弦纹或乳钉纹，体现了早期青铜器的装饰风格。合金比例中铜含量较高，锡含量较低，使器物质地相对柔软，便于加工但强度较低。铸造完成后可能经过简单的打磨处理。',
        en_desc: 'An early Shang Dynasty (1600-1046 BCE) bronze wine vessel. The bronze jue is one of the earliest bronze wine vessels of the Shang Dynasty and an important component of the Shang ritual vessel system. Shang society highly valued sacrificial activities, and wine vessels played a key role in rituals. The jue\'s form is scientifically and rationally designed - the spout facilitates pouring, the tail prevents wine spillage, and the pillars could be used for hanging decorations or fixation. The three-legged design is not only stable but also facilitates heating wine over fire. The appearance of bronze jue marks the beginning of China\'s Bronze Age and is an important symbol of Chinese civilization entering an advanced stage. The vessel has a spout at the front, a tail at the back, pillars in the middle, and three legs. It was a basic vessel for warming or drinking wine among Shang Dynasty bronze ritual objects. Uses early bronze casting technology, employing simple two-part or composite molds. The vessel walls are relatively thin, reflecting the characteristics of early bronze casting technology. Components like the spout, tail, and legs may have been made using separate casting and then connected to the vessel body. The surface decoration is simple, mostly string patterns or nail patterns, reflecting the decorative style of early bronzes. The alloy ratio has higher copper content and lower tin content, making the vessel relatively soft and easy to process but with lower strength. After casting completion, it may have undergone simple polishing treatment.'
    },
    {
        id: 'tang-court-lady-figurine',
        zh_name: '唐代仕女造像',
        en_name: 'Tang Dynasty Court Lady Figurine',
        image: 'images/tang_lady_thumb.png',
        model: 'models/statuette.glb',
        zh_desc: '唐代墓葬出土的陶质仕女俑。唐代仕女俑是唐代社会文化和审美观念的重要载体。盛唐时期国力强盛，社会风气开放，女性地位相对较高，丰腴的体态被视为健康和富贵的象征。仕女俑多出土于中上层阶级墓葬，反映了当时社会对女性美的标准和贵族生活方式。这些陶俑不仅是艺术品，更是研究唐代服饰、化妆、社会习俗的重要实物资料。其面容圆润，体态丰腴，身着华丽服饰，是唐代社会审美风尚的体现。采用精细的陶塑工艺，选用优质陶土，经过揉捏、陈腐等多道工序处理。仕女俑的面部表情温和娴静，体现了唐代女性的理想形象。服饰层次丰富，从内衣到外袍都有精细表现。彩绘工艺精湛，使用矿物颜料绘制服饰图案和面部妆容，能够表现出不同材质的质感。发髻造型精美，可能还使用真发作为装饰。整体制作工艺体现了唐代陶工高超的艺术水平和细腻的表现力。',
        en_desc: 'A pottery court lady figurine unearthed from a Tang Dynasty tomb. Tang Dynasty court lady figurines are important carriers of Tang Dynasty social culture and aesthetic concepts. During the high Tang period, the country was powerful, social atmosphere was open, women had relatively high status, and plump figures were seen as symbols of health and wealth. Court lady figurines are mostly unearthed from middle and upper-class tombs, reflecting the contemporary standards of female beauty and aristocratic lifestyles. These pottery figurines are not only artworks but also important physical materials for studying Tang Dynasty clothing, makeup, and social customs. It has a round face, a plump figure, and gorgeous attire, embodying the aesthetic trends of Tang Dynasty society. Uses fine pottery sculpture techniques, selecting high-quality clay that undergoes multiple processes such as kneading and aging. The court lady figurine\'s facial expression is gentle and serene, reflecting the ideal image of Tang women. The clothing has rich layers, with fine representation from inner garments to outer robes. The painting technique is exquisite, using mineral pigments to draw costume patterns and facial makeup, capable of expressing the texture of different materials. The hairstyle is exquisite and may even use real hair as decoration. The overall production process reflects the superb artistic level and delicate expressive power of Tang potters.'
    }
];
